version: "3.8"

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  application:
    build: .
    command: tail -F /dev/null
    volumes:
      - .:/code
    env_file: env-local.env
    environment:
      - ENVIRONMENT_STAGE=local
    depends_on:
      - db
